export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';
export const GET_CART_RESET = 'GET_CART_RESET';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const ADD_TO_CART_RESET = 'ADD_TO_CART_RESET';

export const REMOVE_CART_ITEM_REQUEST = 'REMOVE_CART_ITEM_REQUEST';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAILURE = 'REMOVE_CART_ITEM_FAILURE';
export const REMOVE_CART_ITEM_RESET = 'REMOVE_CART_ITEM_RESET';

export const INCREASE_CART_ITEM_REQUEST = 'INCREASE_CART_ITEM_REQUEST';
export const INCREASE_CART_ITEM_SUCCESS = 'INCREASE_CART_ITEM_SUCCESS';
export const INCREASE_CART_ITEM_FAILURE = 'INCREASE_CART_ITEM_FAILURE';
export const INCREASE_CART_ITEM_RESET = 'INCREASE_CART_ITEM_RESET';

export const DECREASE_CART_ITEM_REQUEST = 'DECREASE_CART_ITEM_REQUEST';
export const DECREASE_CART_ITEM_SUCCESS = 'DECREASE_CART_ITEM_SUCCESS';
export const DECREASE_CART_ITEM_FAILURE = 'DECREASE_CART_ITEM_FAILURE';
export const DECREASE_CART_ITEM_RESET = 'DECREASE_CART_ITEM_RESET';

export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';